version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD:  # Set a real password here
      MYSQL_DATABASE: IagoDataBaseDocker
      MYSQL_USER: root
      MYSQL_PASSWORD:
    ports:
      - "3307:3306" # Changed from 3306 to 3307 to avoid conflict
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  app:
    build: .
    container_name: springboot_app
    ports:
      - "9090:9090"
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/IagoDataBaseDocker?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD:
      SPRING_JPA_HIBERNATE_DDL-AUTO: update

volumes:
  mysql_data: